const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const { createClient } = require('@supabase/supabase-js');
const { authenticate } = require('../middleware/auth');

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);

router.use(authenticate);

router.get('/:id', async (req, res) => {
  try {
    const userId = req.user.userId;
    const { id } = req.params;

    const { data: record, error } = await supabase
      .from('consent_requests')
      .select('*, records:consent_records(decision, decided_at)')
      .eq('id', id)
      .single();

    if (error || !record) {
      console.error('Record error:', error);
      return res.status(404).json({ error: 'Record not found' });
    }

    if (record.requester_id !== userId && record.recipient_id !== userId) {
      return res.status(403).json({ error: 'Not authorized' });
    }

    const { data: rUser } = await supabase.from('users').select('name, phone').eq('id', record.requester_id).single();
    const { data: rcUser } = await supabase.from('users').select('name, phone').eq('id', record.recipient_id).single();

    const requesterName = (rUser && (rUser.name || rUser.phone)) || 'Unknown';
    const recipientName = (rcUser && (rcUser.name || rcUser.phone)) || 'Unknown';

    let duration = 'No set end time';
    if (record.expires_in_minutes) {
      duration = record.expires_in_minutes >= 60
        ? (record.expires_in_minutes / 60) + ' hour(s)'
        : record.expires_in_minutes + ' minute(s)';
    }

    const doc = new PDFDocument({ margin: 50 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="consent-record-' + id + '.pdf"');
    doc.pipe(res);

    doc.fontSize(22).font('Helvetica-Bold').text('May I - Consent Record', { align: 'center' });
    doc.moveDown();
    doc.fontSize(11).font('Helvetica').text('This is an official timestamped record of a consent request made through the May I app.', { align: 'center' });
    doc.moveDown(2);

    doc.fontSize(13).font('Helvetica-Bold').text('Request Details');
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica');
    doc.text('Record ID: ' + record.id);
    doc.text('Status: ' + record.status);
    const decisionRecord = record.records && record.records[0];
    if (decisionRecord) {
      doc.text('Decision: ' + decisionRecord.decision);
      doc.text('Decision Time: ' + new Date(decisionRecord.decided_at).toLocaleString());
    }
    if (record.note) {
      doc.text('Note: ' + record.note);
    }
    doc.text('Categories: ' + (record.categories || 'None'));
    if (record.note) doc.text('Note: ' + record.note);
    doc.text('Duration: ' + duration);
    doc.text('Created: ' + new Date(record.created_at).toLocaleString('en-US'));
    doc.moveDown(1.5);

    doc.fontSize(13).font('Helvetica-Bold').text('Parties');
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica');
    doc.text('Requester: ' + requesterName);
    doc.text('Recipient: ' + recipientName);
    doc.moveDown(1.5);

    doc.fontSize(13).font('Helvetica-Bold').text('Legal Notice');
    doc.moveDown(0.5);
    doc.fontSize(10).font('Helvetica').text('This record was generated by the May I app and reflects the consent status at the time of the request. Both parties were verified by phone number. This document may be used as evidence of consent in a dispute.');

    doc.end();
  } catch (err) {
    console.error('PDF error:', err);
    res.status(500).json({ error: 'Failed to generate PDF' });
  }
});

module.exports = router;
