const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);

router.get('/:id', async (req, res) => {
  // Allow token via query param for browser-based PDF downloads
  if (req.query.token && !req.headers.authorization) {
    req.headers.authorization = `Bearer ${req.query.token}`;
  }
  try {
    const userId = req.user.id;
    const { id } = req.params;

    const { data: record, error } = await supabase
      .from('consent_requests')
      .select('*, requester:requester_id(name, phone), recipient:recipient_id(name, phone)')
      .eq('id', id)
      .single();

    if (error || !record) return res.status(404).json({ error: 'Record not found' });

    if (record.requester_id !== userId && record.recipient_id !== userId) {
      return res.status(403).json({ error: 'Not authorized' });
    }

    const doc = new PDFDocument({ margin: 50 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="consent-record-${id}.pdf"`);
    doc.pipe(res);

    doc.fontSize(22).font('Helvetica-Bold').text('May I — Consent Record', { align: 'center' });
    doc.moveDown();
    doc.fontSize(11).font('Helvetica').text('This document is an official timestamped record of a consent request made through the May I app.', { align: 'center' });
    doc.moveDown(2);

    doc.fontSize(13).font('Helvetica-Bold').text('Request Details');
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica');
    doc.text(`Record ID: ${record.id}`);
    doc.text(`Status: ${record.status}`);
    doc.text(`Categories: ${record.categories}`);
    if (record.note) doc.text(`Note: ${record.note}`);
    if (record.expires_in_minutes) {
      const duration = record.expires_in_minutes >= 60
        ? (record.expires_in_minutes / 60) + ' hour(s)'
        : record.expires_in_minutes + ' minute(s)';
      doc.text(`Duration: ${duration}`);
    } else {
      doc.text('Duration: No set end time');
    }
    doc.text(`Created: ${new Date(record.created_at).toLocaleString('en-US')}`);
    doc.moveDown(1.5);

    doc.fontSize(13).font('Helvetica-Bold').text('Parties');
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica');
    doc.text(`Requester: ${record.requester?.name || 'Unknown'} (${record.requester?.phone || ''})`);
    doc.text(`Recipient: ${record.recipient?.name || 'Unknown'} (${record.recipient?.phone || ''})`);
    doc.moveDown(1.5);

    doc.fontSize(13).font('Helvetica-Bold').text('Legal Notice');
    doc.moveDown(0.5);
    doc.fontSize(10).font('Helvetica').text('This record was generated by the May I app and reflects the consent status at the time of the request. Both parties were verified by phone number at the time of use. This document may be used as evidence of consent in a dispute.');

    doc.end();
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to generate PDF' });
  }
});

module.exports = router;
